name: WayStones
version: '${project.version}'
author: 'Ugric'
description: 'A plugin that adds waystones to your server, allowing players to teleport between them.'
main: dev.wbell.waystones.WayStones
api-version: '1.20'
softdepend: [DecentHolograms]
commands:
  renamewaystone:
    description: 'Renames a waystone.'
    usage: /renamewaystone <name>
    permission: waystones.rename
permissions:
  waystones.rename:
    description: Allows players to rename Waystones via command
    default: op
  waystones.create:
    description: Allows players to create Waystones
    default: op
  waystones.use:
    description: Allows players to use Waystones
    default: op
folia-supported: true